### ISSUE TITLE
Support `-t, --build-test`

### ISSUE THREAD

**Issue by samoht** [ocaml/opam-depext#10]
Would be nice to install external dependency when installing the packages needed for testing. See https://travis-ci.org/mirage/irmin/builds/57455158 and https://github.com/mirage/irmin/pull/183#issuecomment-90482330

**Comment by samoht** [comment]
ping?

**Comment by AltGr** [comment]
Sadly, OPAM doesn't provide the `--build-{test,doc}` options to `opam list`. Thankfully, they can be accessed through the env, using `OPAMBUILDTEST` and `OPAMBUILDDOC`.
So you can simply write:

```
OPAMBUILDTEST=1 opam depext ...
```

Since there is this workaround, I'd prefer to properly add the option to OPAM and make depext forward it rather than adding it to depext and hacking through the env.

**Comment by samoht** [comment]
The workaround seems to work very well, thanks!

**Comment by rjbou** [comment]
External dependencies handling is integrated in opam (since [2.1.0-alpha](https://github.com/ocaml/opam/releases/tag/2.1.0-alpha)). If this is still an issue, please open one in [opam](https://github.com/ocaml/opam/issues) bugtracker.
Thanks!
