### ISSUE TITLE
Make `2.0` the default branch

### ISSUE THREAD

**Issue by carlosdagos** [ocaml/opam-depext#122]
Hello,

I think it'd be nice to make [`2.0`](https://github.com/ocaml/opam-depext/tree/2.0) the default repository branch, since it makes finding the effort being done in https://github.com/ocaml/opam/pull/3975 a bit easier.

With that said, is this repository still accepting PRs? At the time of writing https://github.com/ocaml/opam/pull/3975 isn't merged and I'd like to discuss a potential change to `opam-depext` (which could make its way onto https://github.com/ocaml/opam/pull/3975). 

Thank you :smile:

**Comment by XVilka** [comment]
Or merge it in the master like the similar situation in opam-publish: https://github.com/ocaml/opam-publish/pull/85

**Comment by rjbou** [comment]
Agree on merging/setting 2.0 default branch, it's less confusing, plus the notice is only in e 2.0 branch readme.

The repo is not yet frozen (because the depext PR is still open), but we won't update the plugin (unless critical bug fix for ex.).

We can discuss on these changes in the dedicated [opam issue](https://github.com/ocaml/opam/issues/3790)

**Comment by dra27** [comment]
Default branch has been 2.0 for a while - at this stage it's probably fine just to leave the repo as somewhat strangely having two branches?!

**Comment by rjbou** [comment]
Agree!
