### ISSUE TITLE
opam var error with opam 2.1.0

### ISSUE THREAD

**Issue by rjbou** [ocaml/opam-depext#124]
opam var exit code changed in opam 2.1.0, it results on an error of opam depext call.
```
$ opam depext
[ERROR] Variable arch not found
Fatal error: exception Depext.Fatal_error("Command failed: opam var arch --readonly returned 5", 5)
```
Repository packages disabled depext for 2.1.0 cf https://github.com/ocaml/opam-repository/pull/16325

**Comment by rjbou** [comment]
The errors comes from `opam var` behavior changes: in the 2.1.0-alpha, `opam config var` remained unchanged, but `opam var` need to act on a scope, and default is switch, while `arch` is a global variable.

**Comment by AltGr** [comment]
For options, we already select the scope automatically ; for _reading_ variables it's probably good as well, since that's how resolution is done in practice in files etc.
Writing to variables becomes more complex though, because you are allowed to create new ones. We should probably issue a warning on `opam var foo=bar` before creating a switch-scope `foo` variable that shadows a global-scope `foo` variable, to avoid surprises when changing switch later on.

EDIT: that is more a comment for opam itself though.
