### ISSUE TITLE
no uninstall command

### ISSUE THREAD

**Issue by UnixJunkie** [ocaml/opam-depext#17]
opam-depext can install things, but sometimes things can go wrong and needs to be reverted: an uninstall command should be provided.

**Comment by AltGr** [comment]
That sounds very difficult: we would need to add a state to register what we installed and how it went, and then, check that no dependent packages have been installed meanwhile before trying to uninstall. Would providing more explicit messages at install time do the trick ?

**Comment by avsm** [comment]
see avsm/opam-installext#2 for an improvement on Debian that helps with uninstall

**Comment by AltGr** [comment]
Indeed, that's a very good idea!
I was actually going to add that even in normal use of `apt-get`, I am often annoyed by the lack of a real revert option (I have to find the list of packages that actually got installed in the backlog to remove them...) ; but François' idea of using equivs is very promising.

What about other package managers though ?

**Comment by mcp292** [comment]
I second this motion. 

Instead of dealing with keeping track of what you installed, how it went, and what packages now need it, couldn't you just uninstall all the packages installed when running opam depext _package_? If depext checks if a package is already installed before installing, then the remove command can only remove if the package is listed as a dependency. If any of the removed packages were actually needed by other packages on the system you could resolve dependencies with the os package manager.

**Comment by rjbou** [comment]
External dependencies handling is integrated in opam (since [2.1.0-alpha](https://github.com/ocaml/opam/releases/tag/2.1.0-alpha)). If this is still an issue, please open one in [opam](https://github.com/ocaml/opam/issues) bugtracker.
Thanks!
