### ISSUE TITLE
Recursive depext

### ISSUE THREAD

**Issue by AltGr** [ocaml/opam-depext#2]
Latest version uses cmdliner, which is very nice, for command-line parsing.

A big issue with this, though, is that cmdliner itself depends on ocamlfind ; and ocamlfind depends on m4, which is a depext. It's problematic to have depexts for `opam-depext` itself. Workarounds could include:
- somehow including a stand-alone version of cmdliner (a la opam 'make lib-ext')
- getting rid of the dependency in ocamlfind
- removing usage of cmdliner :(

Other ideas ? @avsm, @dbuenzli ?

**Comment by dbuenzli** [comment]
Since `cmdliner` has no dependency and uses `.install` files to install, it should be possible to make `cmdliner` independent of `ocamlfind`. Just need to remove the useless `-use-ocamlfind` of ocamlbuild in `topkg` and even I think ocamlbuild works with that option even if it cannot find `ocamlfind`.  

So basically if you remove the dependency on `ocamlfind` in `cmdliner`'s `opam` file in the opam repo everything should work. 

Initially I was publishing my packages that didn't depend on anything without the dep on `ocamlfind` but I don't remember why I had to put the dep on `ocamlfind` again (I vaguely remember an `oasis` related problem when I still used that).

**Comment by AltGr** [comment]
Awesome! That'd be the best, if possible.
I'll try and report back.

**Comment by AltGr** [comment]
No luck, ocamlbuild doesn't collaborate that easily:

```
Failure: ocamlfind not found on path, but -no-ocamlfind not used.
```

Removing `-use-ocamlfind` from topkg works, though.

**Comment by dbuenzli** [comment]
You can simply use `Other ("ocamlbuild -classic-display", "_build")` for `builder`  [here](https://github.com/dbuenzli/cmdliner/blob/master/pkg/build.ml#L6). Patch or issue in `cmdliner` welcome.

**Comment by AltGr** [comment]
Ok, will do !

**Comment by dbuenzli** [comment]
[cmdliner 0.9.7](https://github.com/dbuenzli/cmdliner/blob/v0.9.7/CHANGES.md#v097-2015-02-06-la-forclaz-vs) should be your friend.

**Comment by AltGr** [comment]
Just saw that: thanks!
