### ISSUE TITLE
opam depext is slow at doing nothing

### ISSUE THREAD

**Issue by Drup** [ocaml/opam-depext#31]
I don't know if this is specific to archlinux, but `opam depext` takes forever when it has nothing to do. It is especially striking compared to `opam install` which is very quick when there is nothing to do.

A quick look at `htop` makes it look like `opam list` calls are costly.  Maybe related to https://github.com/ocaml/opam/issues/1817 ?

**Comment by AltGr** [comment]
I've pending PRs on opam that include the package descriptions in the opam files, and in the opam cache -- so there will be no need to search and read all packages' description files anymore. This should make `opam list` instant (note that `opam list --short` doesn't need them, but I am not sure they're not loaded anyways).

We have different levels of optimisation for the call to the system package manager depending on the distribution too, we do a [single call](https://github.com/ocaml/opam-depext/blob/fc183489fb9ee2265b6d969fcab846d38bceb937/depext.ml#L221) for apt-get (although 0.7 had a regression in this regard) and homebrew, but [a call per package](https://github.com/ocaml/opam-depext/blob/fc183489fb9ee2265b6d969fcab846d38bceb937/depext.ml#L235) on most distributions, because it's easier to implement and ensure compatibility this way. Contributions are very welcome to implement single-command lookups for other distributions!

**Comment by UnixJunkie** [comment]
While we are at it: opam update is super slow too.
Last time I launched it under strace, I saw it scans a lot the filesystem.

**Comment by rjbou** [comment]
External dependencies handling is integrated in opam (since [2.1.0-alpha](https://github.com/ocaml/opam/releases/tag/2.1.0-alpha)). If this is still an issue, please open one in [opam](https://github.com/ocaml/opam/issues) bugtracker.
Thanks!
