### ISSUE TITLE
non-interactive depext now goes interactive with `-y`

### ISSUE THREAD

**Issue by avsm** [ocaml/opam-depext#42]
```
$ opam depext -i -j 4 -y mirage mirage-xen mirage-unix
# Detecting depexts using flags: x86_64 linux ubuntu
# The following system packages are needed:
#  - debianutils
#  - libxen-dev
#  - m4
#  - ncurses-dev
#  - perl
#  - pkg-config
#  - time
# The following new OS packages need to be installed: ncurses-dev
The following command needs to be run through "sudo":
    apt-get install ncurses-dev
Allow ? [Y/n] 
```

Shouldnt happen due to the `-y`

**Comment by avsm** [comment]
@AltGr any chance you could look at this?  Its blocking releasing the `-yvj` flags feature in depext.

**Comment by AltGr** [comment]
Sorry for the lag.
Indeed, as documented, `--yes` is strictly passed to opam, it's not interpreted by `depext` itself. But since `depext` itself has now been made interactive, this is a bit misleading.

You can use `--noninteractive` (which is the default when not running from a tty) instead. I agree that the CLI could be improved.

**Comment by avsm** [comment]
Why not just combine `--yes` and `--noninteractive`?
