### ISSUE TITLE
Support version constraints

### ISSUE THREAD

**Issue by dsheets** [ocaml/opam-depext#43]
It would be nice to be able to query/restrict depexts to specific versions for systems that have multiple versions available or for better error messages with package managers that have a single available version.

**Comment by dsheets** [comment]
One possible alternative is to have system-wide filters so that one could specify different behavior for, e.g., Ubuntu 12.10 vs 16.04 or OS X 10.9 vs 10.11.

**Comment by craff** [comment]
It would be better to have contraints on package version, because it would for instance allow to generate a debian package from an opam package. Actually, I think the depexts field should contain for each distro what is needed to generate distro specific package from opam package.

**Comment by AltGr** [comment]
The specification, opam-wise, is very generic: we are now focused on arch/os/distribution, but we could actually extract any number of criteria from a given machine (e.g. `["i386"; "linux"; "ubuntu"; "16.04"]`, or maybe `["i386"; "OSX"; "Darwin"; "major=10";"minor=11"]`). This extraction is the job of `opam-depext`, and it can easily be extended. It would actually make a lot of sense to separate it from the code that takes action on packages, using each known package manager. This could be a first step of backporting to opam: include depext selection to display the system packages needed to the users, for their specific system.

Then of course, it is a matter of using the right selectors in the repository. Since package depexts are pairs `[selectors] [packages]`, where `packages` get selected as soon as `selectors` is _a subset_ of the currently active criteria (see [the doc](http://opam.ocaml.org/doc/Manual.html#opamfield-depexts)).

Likewise, `packages` are strings that are passed verbatim to the system package managers, so package versions can be included if the package manager allows it.

**Comment by AltGr** [comment]
(the [OS detection code](https://github.com/ocaml/opam-depext/blob/8be303ac793e6b16d5ad3126b1df9b2d98ea353f/depext.ml#L68-L128) is quite straightforward)

**Comment by hcarty** [comment]
I've been bit by this a lot recently with opam-repository, depext and alpine.  Is depext remaining an external opam tool for opam 2.x or is it being integrated into opam itself?  If I can find time to work on this would a contribution be welcome?

**Comment by AltGr** [comment]
It's intended to be integrated mid-term; but I specifically prefer that we settle on the format of depexts to fix issues like this one before that integration is started. See [this ticket on opam](https://github.com/ocaml/opam/issues/2919) for an in-depth discussion.

Thanks a lot for offering to contribute, if you can help settle on a better format for depexts, it would already be very helpful. We need that part before I can be more specific on where help is needed !
See also #63, about Alpine.

**Comment by rjbou** [comment]
External dependencies handling is integrated in opam (since [2.1.0-alpha](https://github.com/ocaml/opam/releases/tag/2.1.0-alpha)). If this is still an issue, please open one in [opam](https://github.com/ocaml/opam/issues) bugtracker.
Thanks!
