### ISSUE TITLE
Check if dependencies are already satisfied before trying to install them.

### ISSUE THREAD

**Issue by mmaker** [ocaml/opam-depext#44]
On my debian is particoularly annoyng that I have to type my user's password everytime my package gets built, because opam tries to install with apt always the same packages. 

It would be nice if opam-depext could check if dependencies are already satisfied with dkpg (which requires no root permission) and skip the installation if so.

**Comment by AltGr** [comment]
Actually, recent version do. But there are some limitations, in particular with Debian, where there can be package aliasings due to "virtual packages":

for example, `conf-ncurses` has a depext on debian package `ncurses-dev`. Except that this package is virtual, and as such doesn't really exist for dpkg:

```
% dpkg-query -W -f '${Package} ${Status}' ncurses-dev
ncurses-dev unknown ok not-installed
```

But:

```
% sudo apt-get install ncurses-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'libncurses5-dev' instead of 'ncurses-dev'
libncurses5-dev is already the newest version.
```

The `dpkg-query` command is the one used by `opam-depext`. See how the `apt-get` command redirects to `libncurses5-dev` instead of the original package.

I see two possible solutions:
- find a way to query `dpkg` for installed aliases (or at least to resolve them)
- don't use virtual packages in depexts, and report to the package repository. Note that this could be harmful to compatibility across versions of the distribution, though (assuming, of course, any instance of the virtual package was OK -- if not this would actually be beneficial)

**Comment by mato** [comment]
`grep-status` -- part of the `dctrl-tools` package ([github](https://github.com/ajkaijanaho/dctrl-tools)) and available in Debian and Ubuntu repositories -- is a more flexible set of command line tools to query the installed package database. Reading the manpage and experimenting a bit, the following runes work for me:

```
$ grep-status -w -FPackage ncurses-dev --or -w -FProvides ncurses-dev -sPackage -sStatus
Package: libncurses5-dev
Status: install ok installed
```

Translation: List installed (implied?) packages whose `Package` or `Provides` field contains a whole package name (`-w`) matching `ncurses-dev`, output the `Package` and `Status` fields of any matches found.

**Comment by AltGr** [comment]
@mato thanks, that's good news. It's a bit annoying that `dctrl-tools` isn't installed by default though (or is it ?), as `opam-depext` can't rely on depexts: we would need to dynamically install it when needed.

**Comment by mato** [comment]
@AltGr `dctrl-tools` is indeed not installed by default. However, it seems to be widely available (I checked e.g. Ubuntu repositories as far back as 12.04LTS), so dynamic installation is possible. The other option I can think of is parsing `/var/lib/dpkg/status` manually to resolve virtual packages.
