### ISSUE TITLE
support the `--yes` option

### ISSUE THREAD

**Issue by samoht** [ocaml/opam-depext#5]
Would be easier to use it in scripts using other opam commands.

**Comment by bradisbell** [comment]
Agreed, this would be very helpful!  Is there any alternative in the mean time?

**Comment by dbuenzli** [comment]
> Agreed, this would be very helpful! Is there any alternative in the mean time?

Doesn't `yes | opam-depext` work ?

**Comment by avsm** [comment]
`OPAMYES=1 opam depext -i foo`

**Comment by AltGr** [comment]
Err... `opam depext` doesn't ask any questions, does it ?
@avsm: it actually doesn't depend on opam-lib (to keep its dependencies to a minimum, and in particular avoid any external dependencies), so that won't work on depext directly. It does call `opam` subprocesses though, so they may be affected. But it's normally just `--version` and `list`.

The only point I can see is when using `opam depext -i`; but in this case, shouldn't we transfer _all_ possible opam options to the opam subprocess ?

**Comment by avsm** [comment]
On 23 Oct 2015, at 00:26, Louis Gesbert notifications@github.com wrote:

> The only point I can see is when using opam depext -i; but in this case, shouldn't we transfer all possible opam options to the opam subprocess ?

yes!
