### ISSUE TITLE
local use

### ISSUE THREAD

**Issue by fxfactorial** [ocaml/opam-depext#54]
I have a depext usage of ["source" "linux" "osx"] and I want to test it locally but not finding a way, even with opam pin. 

Is this feature supported?

**Comment by AltGr** [comment]
If you're still after the answer:
tags are an `AND`, so `"linux" "osx"` is unlikely to ever match.
Pinning your package should otherwise work: use `opam-depext PKG` to check for your current system's flags (as listed by `opam-depext --flags`), or `opam list --external=TAGS PKG` to only list the inferred system packages names.
